suppressPackageStartupMessages({
    library(alabaster.sce)
    library(arrow)
    library(AUCell)
    library(dplyr)
    library(BiocParallel)
    library(BiocSingular)
    library(concaveman)
    library(ggnewscale)
    library(ggplot2)
    library(ggpmisc)
    library(ggrastr)
    library(HDF5Array)
    library(InSituType)
    library(jsonlite)
    library(Matrix)
    library(matrixStats)
    library(pals)
    library(patchwork)
    library(RANN)
    library(reticulate)
    library(RSpectra)
    library(scater)
    library(scran)
    library(scuttle)
    library(Seurat)
    library(sf)
    library(SingleCellExperiment)
    library(slingshot)
    library(sp)
    library(SparseArray)
    library(tidyr)
    library(zellkonverter)
    library(zoo)
})
writeLines(capture.output(sessionInfo()), args[[1]])

#if (!require(bm <- "BiocManager", quietly=TRUE)) install.packages(bm)

#BiocManager::install(c(
#    "alabaster.sce", "arrow", "AUCell", "dplyr", "BiocParallel", "BiocSingular", "concaveman", 
#    "ggnewscale", "ggplot2", "ggpmisc", "ggrastr", "HDF5Array", "InSituType", "jsonlite", "Matrix",
#    "matrixStats", "pals", "patchwork", "RANN", "reticulate", "RSpectra", "scater", "scran", "scuttle", 
#    "Seurat", "sf", "SingleCellExperiment", "slingshot", "sp", "SparseArray", "tidyr", "zellkonverter", "zoo"))